version: '3.8'

services:
  app:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npx create-react-app celula && cd celula && npm start"
